### ISSUE TITLE
Search and filter options don't work for account-sidesheet.component 

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#100]
Hello,

It seems like the search and filter options are broken for account-sidesheet.component.
None of these options get appended to the request url:
https://..../apiserverdev/portal/person/4077bbd6-a19f-43c4-9f64-eb108bf023aa/accounts
They work fine in the accounts.component.

Regards,
Niels

**Comment by Mathnstein** [comment]
Hi @NielsDeGroot - could you provide a repro for this or attach some screenshots?

I believe I've found what you're discussing, but the table within the sidesheet does correctly filter & etc, although this table is grabbing different data through a different endpoint than what you are referring to.

**Comment by NielsDeGroot** [comment]
Thank you for the quick reply.

Log in with a person who is manager (UID_PersonHead@Person)

'My Direct Reports' > Pick a person
The sidesheet opens then select the 'Memberships' tab

The section 'User accounts' is the first in the list and pulls in the accounts of that person
https://itshop.groot.net/apiserverdev/portal/person/4077bbd6-a19f-43c4-9f64-eb108bf023aa/accounts

Insert something in the Search bar: Test
The unfiltered list is show again and you can also see that the api call is unchanged:
https://itshop.groot.net/apiserverdev/portal/person/4077bbd6-a19f-43c4-9f64-eb108bf023aa/accounts

When you select an other section in the 'Memberships' tab for instance 'System roles'
https://itshop.groot.net/apiserverdev/portal/person/4077bbd6-a19f-43c4-9f64-eb108bf023aa/rolememberships/ESet?PageSize=20

Insert something in the Search bar: Test
You can see that the search is added to the api call:
https://itshop.groot.net/apiserverdev/portal/person/4077bbd6-a19f-43c4-9f64-eb108bf023aa/rolememberships/ESet?PageSize=20&search=Test

![BrokenSearchBarUserAccounts](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/3f89b841-a4ec-437b-86b5-ff9b9463a56e)

**Comment by NielsDeGroot** [comment]
Hello Cody,

I've updated the issue.

**Comment by Mathnstein** [comment]
@NielsDeGroot yes this is definitely a bug. Good catch and thanks for the detailed repro! Internal ticket created with 444602.
