### ISSUE TITLE
v92, latest: Cart items with confirmed params are not deleted from cart even if you cancel the product details sidesheet

### ISSUE THREAD

**Issue by juancarloscamargo** [OneIdentity/IdentityManager.Imx#102]
Steps to reproduce:

- Created a Service Item with mandatory request parameters.
- Added the service item to the cart, the product details sidesheet opens with the request parameters.
- Parameters accepted, but request not sent.
- Cancel the request details panel by clicking the X on the upper right corner, a dialog asks if you want to cancel the request.
- Pressing Yes (to cancel) will popup a message "X products have been successfuly added to the cart"

If the parameters were not accepted, canceling the details panel will render the correct results and no product would be added.
In cart-items.service.ts, BulkitemsStatus.saved is true after accepting the parameters, so even though you cancel the details panel, the item would be added.

**Comment by Mathnstein** [comment]
Good corner case - internal ticket created: 444465

**Comment by juancarloscamargo** [comment]
This could help somehow?
v92 imxweb/projects/qer/src/lib/shopping-cart/cart-items.service.ts
- 240:          if (item.status === BulkItemStatus.saved) {
+240:          if (item.status === BulkItemStatus.saved && results.submit) {
