### ISSUE TITLE
Helpdeskmodule - Endpoint does not exist on the backend

### ISSUE THREAD

**Issue by mru-ipg** [OneIdentity/IdentityManager.Imx#103]
Endpoint does not exist on the Backend

**Comment by mru-ipg** [comment]
On the Component of the HDS-Project
this.entitySchema = this.hdsApiService.typedClient.PortalCalls.GetSchema();
The hdsApiService is serving an Error because of 404 it seems like the Endpoint does not exist on the backend.

![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/f018f0a4-8963-4fca-8dda-154d54bec16c)


![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/96bf8cae-7ace-4da0-bed5-216e6c3448ac)

**Comment by Mathnstein** [comment]
Hi @mru-ipg  - I'm not sure how you wound up in a state where you have the frontend built but without the api endpoints but I would re build the HDS project.

> Build ./HDS/build.proj --> Produces the imx-api-hds.tgz that then will go into the assemblies folder and expose endpoints to the server

Then rebuild and serve the frontend

> npm run build:watch:dynamic hds --> This part I think you already had correct but its an additional verification step, this should fail if the imx-api or endpoints don't exist.

**Comment by mru-ipg** [comment]
/HDS/build.proj and where to find this file, coul you provide more information, the Angular part is working fine but the Endpoint does not exist like a dll ore something

**Comment by Mathnstein** [comment]
Apologies - Ignore my comment on building the imx-api-hds, that is already available on the repo here.

Grab this file from the repo here under imxweb/imx-modules/imx-api-hds.tgz, and stick that in your assemblies folder under Assemblies/imx-modules.

Then restart your server (locally or remote), this should give you the endpoints in the admin portal/swagger api documentation.

My suspicion is that the package was missing or had built incorrectly such that your final assemblies didn't have it loaded.

**Comment by mru-ipg** [comment]
I mean the tgz file provides just TypeScript Classes and Interfaces for the Frontend, either is here the problem that a .dll file does not exist which is responsible for the hds module.

PS: The .dll file ist responsible to show up an endpoint in the swagger, like we do it when we create a custom endpoint. I mean there is no dll for the Hds module

**Comment by Mathnstein** [comment]
I see - yes the issue is further back and not related to the github code, it may be that the HDS module is not installed in your database or that the API plugin is not loaded.

For handling of installations / setup I'd refer you to the [setup guide](https://support.oneidentity.com/de-de/technical-documents/identity-manager/9.2/help-desk-module-user-guide).

If this is not helpful then I would suggest opening a [support ticket](https://support.oneidentity.com/).

Apologies for the red herring ;)
