### ISSUE TITLE
Typo in Identity Manager 9.2 - HTML5 Development Guide

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#104]
Typo in Identity Manager 9.2 - HTML5 Development Guide

Page 1:
Table 1: Angular libraries

Name	Type 			Dependencies within the workspace
qbm		Angular library	none
qer		Angular library	**qer**

Should be:

qer		Angular library	**qbm**

This maybe be confusing when you are just starting out with the HTML applications ;-)

LoL
Niels

**Comment by Mathnstein** [comment]
Hi @NielsDeGroot  - I've passed this off to our tech writer to handle. It is associated with this ticket ID: 444566. But we may not explicitly mention this in an upcoming release notes, given its just a typo ;)
