### ISSUE TITLE
Typo in Identity Manager 9.2 - API Development Guide

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#105]
https://support.oneidentity.com/technical-documents/identity-manager/9.2/api-development-guide/11#TOPIC-2085523
9. Copy the imx-api-ccc.tgz to the **bin\imxweb** subfolder of your IIS installation.
11. Restart the API Server and ensure that the imx-api-ccc.tgz file is in the **bin\imxweb** folder of your IIS installation.

bin\imxweb should be: bin\imx-modules

9. Copy the imx-api-ccc.tgz to the **bin\imx-modules** subfolder of your IIS installation.
11. Restart the API Server and ensure that the imx-api-ccc.tgz file is in the **bin\imx-modules** folder of your IIS installation.

Regards,
Niels

**Comment by Mathnstein** [comment]
Great catch - passed along as internal ticket 445059
