### ISSUE TITLE
Mandatory reason check in 'qer\request-history' module switched around

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#109]
qer\src\lib\request-history\request-action\request-action.service.ts
In the following function 'createCdrReason' the outcome 'required' parameter is switched around.

Ex. of calling function without a mandatory reason
_const reason = this.createCdrReason();
const reason = this.createCdrReason("#LDS#Additional comments about your decision");_

_private createCdrReason(display: string = '#LDS#Reason for your decision', required: boolean = false): BaseCdr {
    const column = this.entityService.createLocalEntityColumn({
      ColumnName: 'ReasonHead',
      Type: ValType.Text,
      IsMultiLine: true,
      MinLen: required ? 0 : 1,
    });_

DEBUG [main.js:2230] A value for column "ReasonHead" is required 

Should be: _MinLen: required ? 1 : 0,_

Regards,
Niels

**Comment by Mathnstein** [comment]
@NielsDeGroot good catch on backwards logic: Internal bug 445856 created.
