### ISSUE TITLE
Items in the shopping cart arent updated dynamically

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#110]
After having added a product and navigating back to the dashboard the product isn't displayed in the "Products in Shopping Cart" tile without refreshing the page.
This issue can be resolved by calling the reloadPendingItems(); function in the try block of the ngOnInit in the StartComponent. 

![FIx](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/4b2e440a-5016-45e4-ac6f-2686f668e2b9)

**Comment by Mathnstein** [comment]
Created an internal ticket: 446086

**Comment by Mathnstein** [comment]
Created an internal ticket: 446087
