### ISSUE TITLE
Changes in the Identity Hyperview aren't updated until refreshing the page

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#111]
After deactivating an Identity over the "Edit Identity" Sidesheet under the "Organizational Inforamtion" Slider in the "Main Data" Tab the Hyperview shows the Identity as if it was still active until refreshing the page completely.

**Comment by Mathnstein** [comment]
@IPG-GillesRusso I've tried to reproduce this issue and I am seeing the data within the hyperview refresh once you have saved the "main data" changes.

Could you add some clearer repro steps + screen shots of this issue?

**Comment by IPG-GillesRusso** [comment]
Of course let me elaborate a bit more.
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/dd6b6609-7dd2-4616-8b4c-54993ef855d0)
Whenever I edit an identity via my dashboard and manually deactivate this identity the view isn't updated directly let me show my steps with screenshots:
Before deactivating:
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/00542727-3e7d-47a2-9973-b1ced906df02)
Deactivate the person and save:
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/2b37ac83-e511-406e-be75-539d47f32d0f)
And now the hyperview is only updated once I refresh the page completely:
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/3b383e7e-4010-446c-b884-bdf60b755692)
 
I Hope this explenation helps.

**Comment by Mathnstein** [comment]
@IPG-GillesRusso I see - there seems to be a bit of a delay regardless of page load or not. I'll pass this through as an internal ticket to see if that can be improved or if it is a limitation of data propagating through the database.

**Comment by Mathnstein** [comment]
Created an internal ticket: 446143

**Comment by SebastianW-OneIdentity** [comment]
FYI: 
There is no real fix to this bug and this is a limitation due to data propagation through the database. It takes some time for the changes to take effect. 

So the only change with 446143  was to show the better snackbar message 'Your changes have been successfully saved. It may take some time for the changes to take effect.' if the user has changed the IsInactive value of an identity.

**Comment by sebastian-kuebbeler** [comment]
Thank you for the update @SebastianWeberQuest, but your response makes me wonder if you couldn't have a background task checking for updates and then applying them to to view. Is that theoretically possible?
