### ISSUE TITLE
Unable to save the changes to a dynamic business role after adding another condition

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#112]
After adding another condition in the "Edit Business Role" side sheet I am unable to save the changes. The button to save my new condition is not displayed nor clicklable in any way.

**Comment by Mathnstein** [comment]
@IPG-GillesRusso could you elaborate on "adding another condition"?

Please give clearer repro steps / screenshots / gifs where applicable so I can pass these on to be worked on if they are legitimate bugs.

**Comment by IPG-GillesRusso** [comment]
I am going to show you each steps I took until I encountered the problem.
1.	I navigated to the Data Explorer       
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/4b641833-9739-4ee6-9fb8-335226d68381)                                                                                                                                                                                                                                                                                                                                                                                                                          
2.	Choose Business Roles on the side.
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/ef0eb0f2-e228-44e6-a87b-981d817049c7)
3. Edit the Business Role and add a condition
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/1bc433e5-2d4a-4c9c-85b7-fa0a338f9a4c)
4.	Now I am unable to save my change.

**Comment by Mathnstein** [comment]
@IPG-GillesRusso to confirm you are referring to the "Memberships" > "Automatic memberships" tab correct?

At least according to your screenshot, the final condition you added would need to have an operator to be valid.

I'm able to replicate the "save button is broken" on boolean conditions, but I cannot replicate the "save button is missing". I'll go ahead and open an internal ticket to look at that. 

Feel free to add more context to this closed ticket, a developer will refer back to this comment thread when they start investigating.

**Comment by Mathnstein** [comment]
Created an internal ticket: 446295

**Comment by IPG-GillesRusso** [comment]
Yes, exactly thank you very much.

So, I discovered that the issue mainly occurs with conditions that have Boolean values. For example, while checking for external employees.
We have investigated the issue a bit and we think the issue originates from the save(); function in the dynamic-role.component of the role-membership module but we were unable to solve the issue.

I also already opened separate tickets for the issues concerning the wep portal with your technical support.

Thank you very much in advance.
Von: Cody Griffith ***@***.***>
Gesendet: Dienstag, 13. Februar 2024 15:38
An: OneIdentity/IdentityManager.Imx ***@***.***>
Cc: Gilles Russo - IPG ***@***.***>; Mention ***@***.***>
Betreff: Re: [OneIdentity/IdentityManager.Imx] Unable to save the changes to a dynamic business role after adding another condition (Issue #112)


@IPG-GillesRusso<https://github.com/IPG-GillesRusso> to confirm you are referring to the "Memberships" > "Automatic memberships" tab correct?

At least according to your screenshot, the final condition you added would need to have an operator to be valid.

I'm able to replicate the "save button is broken" on unary conditions. I'll go ahead and open an internal ticket to look at that.

Feel free to add more context to this closed ticket, a developer will refer back to this comment thread when they start investigating.
