### ISSUE TITLE
Adding same product twice to shopping cart

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#114]
Use case:
User logs into web portal and adds the same product twice by mistake to the shopping cart.
Product is requestable resource 'QERResource' (just normal resource not Multi-request)

Request > New Request
Product: [v] Resource A
[Add to cart]
Product: [v] Resource A
[Add to cart]
-> Go to cart

| Shopping cart | | | | 
|---|---|---|---|
| Product | Actions | Check result | |		
| Resource A | Edit | Not Checked | [Remove from Cart]
| Resource A | Edit | Not Checked | [Remove from Cart]

User presses on [Submit]

Message: At least one product in your shopping cart cannot be requested.

| Shopping cart | | | | 
|---|---|---|---|
| Product | Actions | Check result | |	
| Resource A | Edit | [Error] | [Remove from Cart]
| Resource A | Edit | [Error] | [Remove from Cart]

User removes one of the same products from the cart: clicks on [Remove from cart]

Message: Remove Product From Cart
Are you sure you want to remove the product from your shopping cart?
[Yes]

| Shopping cart | | | | 
|---|---|---|---|
| Product | Actions | Check result | |	
| Resource A | Edit | [Error] |  [Remove from Cart]

At this point the message: At least one product in your shopping cart cannot be requested.
is still on the screen and the Submit button is still greyed out.
![ShoppingCart](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/bfa2a1f2-4f6b-4f2a-a1d6-f2ad6b09a3a7)

Pressing F5 or going to the dashboard and back in the cart, login off and on again
don't refresh the current status of the shopping cart.

To get rid of this you need to select the (three-dot icon) in the right corner of the Shopping cart and
select 'Check shopping cart'

This is not the best user experience in my opinion
Maybe it is an option to perform the 'Check shopping cart' not only on shoppingcart [submit] but also when a user removes a product [Remove from Cart]?

Regards Niels

**Comment by Mathnstein** [comment]
I agree - the UX could be improved here. Our UX team is currently working on the shopping cart and this will be useful feedback for them.

**Comment by Mathnstein** [comment]
Created an internal ticket: 446294
