### ISSUE TITLE
v92 latest: Fixes for the CDR edit-fk-component and the corresponding formfield status.

### ISSUE THREAD

**Issue by juancarloscamargo** [OneIdentity/IdentityManager.Imx#116]
The CDR **edit-fk-component** does not follow the enabled/disabled status of the corresponding formfield. Hence, if you disable a FK form element, the "Select" button of the component still appears, letting the user pickup an element from the fk list anyway.

Fix:
edit-fk.component.html
--   53:   *ngIf="columnContainer?.canEdit && (isHierarchical || columnContainer?.fkRelations?.length > 1)"
++ 53:   *ngIf="columnContainer?.canEdit && (isHierarchical || columnContainer?.fkRelations?.length > 1) && !control.disabled"

hth!

**Comment by hannobunjes** [comment]
Hi @juancarloscamargo ,

Disabled CDR fields are not supported at this time.

This is because the model for `IEntityColumn` (and its counterpart interface in .NET) have never supported a disabled state. They do however, support a read-only state which is what we are using.

**Comment by juancarloscamargo** [comment]
Hi, @hannoquest 
In our case, we need to disable the UID_Department field if the identity is marked as external. The only way we've found is this in the identity edit/create forms (quick example):

case 'IsExternal':
        if (this.identityForm.controls.IsExternal.value == 1) {
        this.data.selectedIdentity.GetEntity().GetColumn('UID_Department').PutValue('');
        this.identityForm.controls['UID_Department'].disable();
   }

without the fix:
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/12726971/3211b858-b963-42a7-925e-78047c7fc23d)

The field is disabled but the select (seleccionar) button is active, allowing the user to pick an element.

**Comment by Mathnstein** [comment]
While we see this as a simple change, the disabling of cdr fields is not currently supported and we consider this a feature enhancement.

Still thanks for the feedback @juancarloscamargo
