### ISSUE TITLE
The FkHierarchicalDialogComponent only loads elements from a list if they have a parent and this parent is treelevel = 0 

### ISSUE THREAD

**Issue by juancarloscamargo** [OneIdentity/IdentityManager.Imx#117]
This component only loads elements from a list if they have a parent and this parent is treelevel = 0 
I have a field with a list of departments which I'm responsible of:
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/12726971/5b256860-28f6-4540-b9e0-b7f9932366eb)

The list shows 40 candidates, pagesized 20, but the component only shows those whose parent is treelevel = 0

![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/12726971/06fb53fb-90a6-4e85-a167-475996974825)

The overall result :

- If I am responsible of a single deparment under a hierachy, the department is not shown in the pickup list.
- If I am responsible of the root hiearchy , the department is shown.

, hence, I cant create an identity on a dept I'm responsible of , instead must I be responsible of the whole hierarchy.

All departments under my responsability are shown in the My responsabilites tab , however:

![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/12726971/a130927d-937a-4dde-97bc-f62d370ade85)

**Comment by Mathnstein** [comment]
After some internal discussion - I was told asked to have you make this a support ticket @juancarloscamargo.

It needs more clarification, although perhaps we could document better the expected behavior between these two components.

**Comment by juancarloscamargo** [comment]
Will do.

**Comment by Mathnstein** [comment]
Thanks @juancarloscamargo  - I will close this issue here in preference of the support case.
