### ISSUE TITLE
Product not requestable after switching recipients

### ISSUE THREAD

**Issue by iCC-MK** [OneIdentity/IdentityManager.Imx#118]
Branch: v92

**Description**
On the "New Request" page, if I'm not allowed to request a specific product (because it's already been requested for example) and change the recipient, I also can't request the product for the new recipient.
I have to manually refresh the product list in order for the product to be requestable again (for example by switching between service categories).

**Possible solution**
Refresh the product list when changing the recipient.

**Comment by Mathnstein** [comment]
This does look like a stale data bug - good catch

**Comment by Mathnstein** [comment]
Created an internal ticket: 447757
