### ISSUE TITLE
Managers face exception after login because of  change to loadDirectReports, since latest commit 

### ISSUE THREAD

**Issue by asattler** [OneIdentity/IdentityManager.Imx#122]
With the latest commit (Sync repo from v92 to v92 20240115102537 (https://github.com/OneIdentity/IdentityManager.Imx/pull/97))
managers are facing an exception direct after login.
![grafik](https://github.com/OneIdentity/IdentityManager.Imx/assets/1102080/a99d3e1d-add3-4215-a967-03d441dd642a)

The exception comes from the new added line:
`          isinactive: '0'`
added with: https://github.com/OneIdentity/IdentityManager.Imx/blob/v92/imxweb/projects/qer/src/lib/wport/businessowner-chartsummary/businessowner-chartsummary.component.ts#L170

I guess there's an update for QER.CompositionApi.Server.PlugIn.dll which we can't access... 

Please clarify

**Comment by Mathnstein** [comment]
@hannoquest had planned to add info on this to the readme. It appears its a breaking change in the api.

**Comment by Mathnstein** [comment]
@hannoquest is this still an issue or can it be closed out?

**Comment by asattler** [comment]
At least I can tell that you need Hotfix for #441320 to resolve the issue. Otherwise you would need to remove the mentioned line from my original message.
