### ISSUE TITLE
newrequest/allProducts: Paginator disappears for last product overview page.

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#123]
In this test-case I have 23 products under Root category (all products)
So slightly more than default of 20 entries per page.

Now when I click on the 'Next Page' the last three products get displayed.
Then click on the 'Dashboard' page and click on 'Request product'

Or alternatively:

Click on 'Go to cart' (so empty cart) and then click on 'Start new request' 

Result: 

The 'newrequest/allProducts' page still shows the last/current page, but now the paginator options are gone.
To get them back you have to force a refresh: F5.

![1](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/cf89280f-b644-4915-b324-6233cd49b35e)
![2](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/243b4f1e-d1c0-417b-a7cd-fdad9f622700)
![3](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/6915139b-2d6a-439e-b147-286700f6fecc)
![4](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/7ea09555-dc64-429f-ab56-727178f1550a)

Regards,
Niels

**Comment by juancarloscamargo** [comment]
Can't reproduce it, Niels. My list have more than 23 products, far more. If I go to the last page , then return to the dashboard via link or to the empty cart and start a new request, the paginator works fine. 
I dont know if it is related, but do you have any api customization on the product item list method?
Running v92 branch from Jan, 16th.

**Comment by NielsDeGroot** [comment]
Hello Juan Carlos,

Thank you for double-checking this. Strange I can reproduce this on:
- A clean install with the OOTB front-end from OneIdentityManager.9.2.zip
- The v92 branch from Feb 28.

I think this is also related to this stale data issue: [https://github.com/OneIdentity/IdentityManager.Imx/issues/118](url)
So I will close it and wait until ticket 447757 is fixed.

Thank you,
Niels
