### ISSUE TITLE
newrequest/allProducts: After 'Add to cart' shopping cart icon is not displayed.

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#124]
After you select a product and click on 'Add to Cart' the shopping cart icon is not displayed
for that product. (so the: Icon with display text: This product is already in your shopping cart)

Regards,
Niels

![a](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/4096e42f-be55-46ad-9920-07bdf794cdc2)
To display the Cart Icon you can use the paginator click on Next  page and then back to the Previous page:
![b](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/d04be0d4-f9ad-409e-ba44-59f0feec9ca4)
![c](https://github.com/OneIdentity/IdentityManager.Imx/assets/53940444/104a1793-a545-4e7b-b9e3-13ca2554fce9)

**Comment by Mathnstein** [comment]
This is another manifestation of stale data from #118 - I'll add this as another aspect to the internal ticket 447757
