### ISSUE TITLE
Console warning: Unknown notification type: CountProductsInShoppingCart 

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#125]
This console warning appears 20-30 sec. after adding a product to the Shopping cart.

main.61170080e2456fae.js:1 2024-03-04T13:02:13.852Z WARN [main.61170080e2456fae.js:1]
Unknown notification type: CountProductsInShoppingCart 

Regards,
Niels

**Comment by Mathnstein** [comment]
Looks like this should be a getter property on the start component. I'll have it looked into.

**Comment by Mathnstein** [comment]
Created an internal ticket: 448524
