### ISSUE TITLE
Is there any way to disable this warning, which blocks us from accessing the Web Portal during development.

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#126]
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/116571901/f136fcea-2c91-4d78-bd39-cc3bb851827b)

After starting the Api Server with the imxclient and compiling qer/qbm, running the qer-app-portal and logging in using the "Identity" authentication method this message is displayed during development. Is there any way to disable/bypass this message?

**Comment by hannobunjes** [comment]
Hi @IPG-GillesRusso 
Your API Server is not configured with a trusted source key. This must be done so that SQL queries created by API Server are trusted. Support will be able to provide more guidance.
