### ISSUE TITLE
Incorrect property binding in bulk-property-editor.component.html

### ISSUE THREAD

**Issue by seeba8** [OneIdentity/IdentityManager.Imx#131]
https://github.com/OneIdentity/IdentityManager.Imx/blob/382c13c8e45370ae54cd18ab00117e4bfc0d4554/imxweb/projects/qbm/src/lib/bulk-property-editor/bulk-property-editor.component.html#L4

This should probably be:
```html
[attr.data-imx-identifier]="'bulk-item' + i"
```
Otherwise, the identifier will indeed be `'bulk-item' + i` multiple times, instead of the expected `bulk-item0`, `bulk-item1` etc.

I have not tested whether this causes any problems, I just noticed it while looking at the developer tools.

**Comment by Mathnstein** [comment]
Created an internal ticket: 453126
