### ISSUE TITLE
Disabling "Hardware" ConfigParm (Preprocessor "MAC") does not lead to removal of menu entries for hardware management

### ISSUE THREAD

**Issue by asattler** [OneIdentity/IdentityManager.Imx#135]
Hi guys,

I just noticed that disabling the ConfigParm "Hardware" does not lead to the removal of the menu entries for device management.
This seems wrong to me, as I would assume that Preprocessor Conditions may have such an effect.

As I've never met a customer which is using the device management (I am sure there are, but I've seen a lot and all of those didn't), I see the regular usecase of hiding those menu entries.
So it would be great if you could ootb either respect the preprop for adding the menu entries (and also the stuff in my-responsibilities) or introduce a configuration parameter to manage those using the AdminPortal.

PS: before you ask: "ServerConfig/DeviceConfig/VI_Hardware_Enabled" doesn't have an effect on this too....

Hope my case is explained clearly ;-)

BR

Andreas

**Comment by SebastianW-OneIdentity** [comment]
Hi @asattler,

You're right! Right now we do not check any ConfigParam before adding the Menu entries for the device management. --> Internal ticket 455930

And we only check the configuration parameter "ServerConfig/DeviceConfig/VI_Hardware_Enabled" in the context of adding the "Devices" entry on the My Responsibilities page, but the menu entry "Device ownership" is still available --> internal ticket 455928
