### ISSUE TITLE
System entitlements: Restoring view with multiple target systems fails

### ISSUE THREAD

**Issue by rogerholtenok** [OneIdentity/IdentityManager.Imx#136]
Hi.

I've had some trouble with saved views that include multiple target systems. I can reproduce the error by doing the following:

1. Filter on multiple target systems:
![bilde](https://github.com/OneIdentity/IdentityManager.Imx/assets/126593949/910071a0-1513-43f9-b61f-98e97597db2b)

2. The target systems show up correctly as separate chips and can be removed:
![bilde](https://github.com/OneIdentity/IdentityManager.Imx/assets/126593949/446bb1e7-b4b5-44c9-b10b-595bb0353454)

3. Save it as a view, reset views, and restore the saved view. The following error message is shown along with an empty chip that can't be removed:
![bilde](https://github.com/OneIdentity/IdentityManager.Imx/assets/126593949/b91aceb0-98ff-44c2-b6d4-b32f83ec038e)

I believe I tracked the problem down to the function `getSelectedFilterFromName` in `imxweb/projects/qbm/src/lib/data-source-toolbar/data-source-toolbar.component.ts`. Target systems are stored as a comma separated string, but the function doesn't split them up before passing them to `findFilterOptionFromValue`. It fails to find the filter option and ends up returning an empty `DataModelFilterOption` object.

Kind regards,
Roger Holten

**Comment by SebastianW-OneIdentity** [comment]
Hi @rogerholtenok,

you're right. This works not like expected. So I've created an internal ticket --> 455931
