### ISSUE TITLE
Rules violations with pending approvals, person list should be filtered by person head or delegated person

### ISSUE THREAD

**Issue by juancarloscamargo** [OneIdentity/IdentityManager.Imx#142]
9.2 latest PR.
Compliance->Rules violations , or dashboard Pending rule violations.
The list shows violations for all users regardless of their manager/person head/delegated person. Thus, I can make a decision on a person I'm not responsible of.
The list should be filtered by ServerConfig/VI_Employee_Person_Filter at the very least.

**Comment by hannobunjes** [comment]
Hi @juancarloscamargo ,
This is intentional, as this view is for the exception approver role, not for the manager role.

**Comment by juancarloscamargo** [comment]
Alternatives are , either reduce the rule scope, or create a rule for every case (more than 100 in my business case)
I'll try an api method config , see if that works, or either an object selection filter.

In the web designer portal, this works as I expected: I have a list of role approvers for the same rule and each one sees a view of the users they can manage and not the whole thing. I'm checking my customizations on that but I'm not sure if I made any.

Thanks!

**Comment by juancarloscamargo** [comment]
A custom api method on portal/rules/violations (API method configuration / rules_violations / Filter condition) did the job. 
Closing.
