### ISSUE TITLE
On several developer instances showing prefix 'Heading' or 'Menu Entry' on Navigation and Titels

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#143]
We have an issue that on several developer instances showing prefix 'Heading' or 'Menu Entry' on Navigation and Titels.
It looks like the translation takes not place at all.
Any language is affected.
Not even the default language or to the two languages that are loaded with the product: en_US , de_DE are working in this situation.

We tried to define the different language setting on the Identity and set the "use language from profil", or we also tried to use the Browser setting, no effect to this issue.

This is a screenshot of the menu and entries that are not translated at all:

!['Heading' and 'Menu Entry' prefix in Angular Portal](https://github.com/OneIdentity/IdentityManager.Imx/assets/107847248/0f27b796-13f9-427c-9f47-5d9fa45cc9d6)

I can verify that the DialogMultiLanguage and the realted entries in QBMTranslationAddOnSource do exists.

How can I troubleshoot this issue

**Comment by hannobunjes** [comment]
Hi @zime-rch 

Please open a support case for this issue.

Thank you.

**Comment by zime-rch** [comment]
Uninstall the upgraded v8.2 ApiServer and re-install ApiServer from the Install Source v9.2 did solve this issue.

**Comment by zime-rch** [comment]
Solved by reinstalling the ApiServer
