### ISSUE TITLE
Sidesheet showing FK columns : No candidate data source for it

### ISSUE THREAD

**Issue by juancarloscamargo** [OneIdentity/IdentityManager.Imx#145]
In v92  I've created a custom api method to handle management of google workspace accounts. I can get a list of the accounts in the GAPuser table and when the user clicks one, there's a sidesheet opening with the details. Everything works fine except when I include a FK column in the sidesheet cols:

```
const cols = ['PrimaryEmail','IsSuspended','UID_Person'];
this.cdrList = this.cdrFactory.buildCdrFromColumnList(this.sidesheetData.selectedGAPAccount.GetEntity(), cols);
```
, the three values are shown:
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/12726971/ba6b3c9d-c38b-4775-86d1-2e3bda6916d5)

but there's that error: No candidate data source for UID_Person/Person.
Question is, could this be related with my custom api method or should I dig deeper in my code. I'm not using the latest v92 pull yet.

**Comment by hannobunjes** [comment]
Hi,
Make sure that the source API for the GAPAccount entity has the UID_Person as a property. Otherwise, the client won't know where to get assignable Person entities from.

**Comment by juancarloscamargo** [comment]
That was it. See Modules\QBM\dvd\Addon\ApiSamples\SDK02_Properties 
Thanks!
