### ISSUE TITLE
Console message: [DOM] Password field is not contained in a form

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#149]
This message is shown in Chrome 
[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq)
<input _ngcontent-ack-c450 class=​"imx-login-input ng-untouched ng-pristine ng-valid" data-imx-identifier=​"login-input-password" type=​"Password" placeholder=​"Password">​

_imxweb/projects/qbm/src/lib/login/login.component.html_

When I wrap the 'input' in a 'form' and  explicitly set the name attribute then the message goes away:

         _<div [hidden]="selectedConfigProvider?.isOAuth2" *ngFor="let authProp of selectedConfigProvider?.authProps" class="imx-loginInput">
            <form>
              <input
                attr.data-imx-identifier="login-input-{{ authProp.name.toLowerCase() }}"
                [type]="authProp.inputType"
                [placeholder]="authProp.display"
                name="name"
                [(ngModel)]="loginData[authProp.name]"
                (keyup.enter)="login()"
                class="imx-login-input"
              />
            </form>
          </div>_

Any thoughts on what this message exactly implies in the first place, and why this is left the way it is in the project?

Thank you,
Niels

**Comment by Mathnstein** [comment]
Hi @NielsDeGroot - nope I think the form wrapper is probably needed and just missing. Good catch!

**Comment by Mathnstein** [comment]
Created an internal ticket: 457721
