### ISSUE TITLE
Only allow certain pilot user to use the new Angular Portal

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#151]
We try to figure out how we can limit the new Angular Portal to a small group of user by using a additional AERole or Systemuser.
Is there a possibility to limit the new angular in this way?
I did not found any configuration parameter.

**Comment by hannobunjes** [comment]
Hi @zime-rch ,

There is an API sample to add access control to a specific app/API project.

You could use a program feature to control access.

``` csharp
using QBM.CompositionApi.Definition;
using QBM.CompositionApi.PlugIns;

namespace QBM.CompositionApi.Sdk01_Basics
{
	public class AccessControl : IApiProviderFor<PortalApiProject>
	{
		public void Build(IApiBuilder builder)
		{
			// Check for a specific program function (QBMFeature) at login time.
			// This example uses the "ApiServer_Admin" function.
			builder.AddPlugin(new CheckFeaturePlugin("ApiServer_Admin"));
		}
	}
}
```

**Comment by zime-rch** [comment]
Hi @hannoquest 

I tried to build such a api but I am not sure what is the value for IApiProviderFor<??>  (is it qer-app-portal ?)

```
using QBM.CompositionApi.Definition;
using QBM.CompositionApi.PlugIns;

namespace QBM.CompositionApi.AccessControlPilot
{
	public class AccessControl : IApiProviderFor<PortalApiProject>	
	{
		public void Build(IApiBuilder builder)
		{
			// Check for a specific program function (QBMFeature) at login time.
			// This example uses the "ApiServer_Admin" function.
			// Created a new feature in QBMFeature: Ident_DialogFeature = ApiServer_Pilot
			builder.AddPlugin(new CheckFeaturePlugin("ApiServer_Pilot"));
		}
	}

}

```

**Comment by hannobunjes** [comment]
Hi @zime-rch ,

For the portal API project, use the interface `IApiProviderFor<PortalApiProject>`.

See also [this section in the API development guide](https://support.oneidentity.com/de-de/technical-documents/identity-manager/9.2/api-development-guide/11#TOPIC-2085524).

**Comment by zime-rch** [comment]
Hi @hannoquest 

Thank you, I will follow the instruction in the manual.

**Comment by zime-rch** [comment]
Hi @hannoquest,

It has worked, issue will be closed:

![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/107847248/b9194139-e0d7-4a07-aa30-7c88af370193)

**Comment by zime-rch** [comment]
closed
