### ISSUE TITLE
Bringing back the shopping cart icon in the masthead

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#153]
Hello @hannoquest 

In this post you hinted that shopping cart in the masthead might return in a future release.
Can you confirm if this is still the case and if so for which release 9.3?

[Shopping cart icon/component OOTB not in top right corner](https://www.oneidentity.com/community/identity-manager/f/forum/36798/apiserver-shopping-cart-icon-component-ootb-not-in-top-right-cornerl)

The customer still wants to bring back the shopping cart. Identical in behavior to webdesigner:
_Shopping cart immediately changes color when product is added to empty cart
and changes back to default color when cart is empty._

Since the masthead component is in the qbm library and all the shopping cart logic is in the qer library.
I'm kind of struggling how to implement this logic without making the qbm library dependent on the qer library.

Regards,
Niels

**Comment by hannobunjes** [comment]
HI @NielsDeGroot ,

This feature is integrated into the 9.3 release.

The masthead is part of `qbm` but you can add an extension directive into the HTML, which acts as a placeholder for child modules.
``` html
  <imx-ext id="mastheadButton"></imx-ext>
```

In the shopping cart module initializer, we use the `ExtService` to register an extension for this ID:

``` typescript
    this.extService.register('mastheadButton', {
      instance: ShoppingCartButtonComponent /* component to display */
    });
```
