### ISSUE TITLE
Set Default Theme not working

### ISSUE THREAD

**Issue by mru-ipg** [OneIdentity/IdentityManager.Imx#154]
Actually is not possible to set a default theme, it throws error!

![default-theme](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/6b8a3e61-ed0b-4223-b445-7667a089ccf0)

**Comment by NielsDeGroot** [comment]
[Custom theme is not applied after being set using the administration portal (4376296)](https://support.oneidentity.com/identity-manager/kb/4376296/custom-theme-is-not-applied-after-being-set-using-the-administration-portal)
