### ISSUE TITLE
Service categories search only returns top level ones

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#156]
When you search for a specific Service category: qer-app-portal/#/newrequest/allProducts
only top level ones will be returned (without parents).
portal/shop/categories?ParentKey=&filter=%5B%5D&search=ChildCategory
The 'Parent=' parameter is always present?

The apicontrol search: [new-request-product.component.ts](https://github.com/OneIdentity/IdentityManager.Imx/blob/v92/imxweb/projects/qer/src/lib/new-request/new-request-product/new-request-product.component.ts)
line 200: const response = await this.categoryApi.get({ ParentKey: '', ...params, ...userParams });

I would prefer if it works like:
const response = await this.categoryApi.get({ ...params, ...userParams });

Is this intentional?

Regards,
Niels

**Comment by zime-rch** [comment]
We have the same issue on searching in the service categorie. Our expectation would be that all subcategories are also listet as search results.

**Comment by hannobunjes** [comment]
Hi @NielsDeGroot , @zime-rch ,
The internal bug ID for this is 459707; expecting a fix to be deployed here soon.
