### ISSUE TITLE
Direct links to products in the new web shop

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#159]
A while ago I asked on the forum about this feature.
https://www.oneidentity.com/community/identity-manager/f/forum/34775/links-to-products-in-the-new-webshop
Is there an estimated time frame for the release of this feature, or is it still on the product backlog and planned for a future release.

Thank you in advance
Gilles

**Comment by hannobunjes** [comment]
Hi @IPG-GillesRusso ,
I just updated the response on the forum.

Thanks,
Hanno
