### ISSUE TITLE
Local imxclient for development not able to do login for qer-app-portal

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#162]
I have a problem whenever I login to the app portal on a local started imxclient.
Ass soon I login with DialogUser Module, I get the following:

`Error: An error occurred while processing the request: POST http://localhost:8182/imx/login/portalSystem.Exception: An error occurred while processing the request: POST http://localhost:8182/imx/login/portal ---> System.InvalidOperationException: Unable to derive connection string from current connection. Call CreateUnauthentifiedConnection instead.`

**Why the imxclient is not able to derive connection string from current connection?**

Screenshot

![image](https://github.com/user-attachments/assets/13611a9d-3f32-42df-92f2-661347853ef8)

**Comment by mru-ipg** [comment]
Try CTRL + Enter pressing during the start, after should be possible to choice another or reset your DB Connection

**Comment by zime-rch** [comment]
> Try CTRL + Enter pressing during the start, after should be possible to choice another or reset your DB Connection

@mru-ipg Thanks, you saved my day. I have used allways my standard global.cfg connection, but since I have added a new connection, it worked fine.
