### ISSUE TITLE
Candidate search: Cannot read properties of undefined

### ISSUE THREAD

**Issue by adnjerem** [OneIdentity/IdentityManager.Imx#163]
There is an issue with the search function of the CDR editor, where sometimes an error gets displayed in the top bar, for example:

> TypeError: Cannot read properties of undefined (reading 'TotalCount')

> TypeError: Cannot read properties of undefined (reading 'Hierarchy')

We found the error in a custom portal where we use the CDR editor, but it can also be reproduced in the IT-Shop.

There is a timing component to the issue, so it doesn't happen all the time. To reproduce it, start typing in a field (in the screen shot below: "h"), then make a short pause such that the browser sends a search request to the backend, then immediately resume typing before the response arrives (in the screenshot below: "ans"). This cancels the first request and triggers a new one, and the error appears.

![image](https://github.com/user-attachments/assets/e3c65df1-2267-49e3-aee0-c404f78c7809)

**Other information**
* Product name: One Identity Manager
* Product version: 9.2 v92-226554

**Comment by adnjerem** [comment]
I found the following snippet in `qbm/.../cdr/edit-fk/edit-fk.components.ts` in the `updateCandidates` function:

```js
const candidateCollection = await this.selectedTable.Get(this.parameters);
this.candidatesTotalCount = candidateCollection?.TotalCount;
 
this.isHierarchical = candidateCollection.Hierarchy != null;
```

It could explain the error message in our custom portal, where the error indicates reading `Hierarchy`, but not the one from the IT-Shop where it reads `TotalCount` and the code correctly uses the null-safe navigation operator.

**Comment by asattler** [comment]
I can confirm this (bad) behavior with cancelling search requests by resuming input in search-input-field (9.2.0 with codebase from commit #146 ).
Would be great to have a fix for that!

**Comment by Mathnstein** [comment]
Great catch - creating a bug for tracking

**Comment by Mathnstein** [comment]
Created an internal ticket: 462445

**Comment by SFagone** [comment]
was this fixed? if so with which version?
I cannot find this number 462445 under resolved issues in the release notes.
@Mathnstein
