### ISSUE TITLE
No incremental compilation with ng build --watch  --configuration development qbm

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#164]
Hello

If I am in development mode in VSCode and I have started the ng build --watch for qbm, denn if I change a file, it will be recognized and he state that the (1) incremental compilation will be started, after that (2) there is a full compilation.

![image](https://github.com/user-attachments/assets/210a3c7d-0136-49e7-8314-f33d1c12f514)

How can I make sure that incremental compilation is really working, otherwise I wait for each changed file a couple of minutes to see the result.

Regards

René

**Comment by Mathnstein** [comment]
Ivy full compilation vs incremental are different topics all together. We use full ivy compilation in our build:
[Difference between partial and full comp](https://stackoverflow.com/questions/72227796/angular-partial-vs-full-compilation-mode)

Incremental is compiling only necessary files that have changes and as the cli states it is doing that - this is the cli handling file hashing and any issues there I would refer to angular help docs on.
