### ISSUE TITLE
The busyservice should have a way to customize the "loading..." message

### ISSUE THREAD

**Issue by juancarloscamargo** [OneIdentity/IdentityManager.Imx#165]
Not a issue, in fact.
The qbm/busyservice shows a "Loading..." message when it is active. But sometimes it is not enough. I mean, if I show it when I am computing sku availability I would like it to say "Computing availability... Stand by". 

Could this message be customized upon calling the beginbusy() function? 

Yes, I know, I am such user...

**Comment by Mathnstein** [comment]
I will tag this as a feature enhancement and create an internal pbi for this - but we often use the loading service from elemental and there is no support for injected text there.

**Comment by Mathnstein** [comment]
Created an internal ticket: 462443
