### ISSUE TITLE
Web Portal Performance problems

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#166]
Even the standard web portal without any customizations can take up to 5 seconds to load. Is there anything we can do to improve its performance. Ideally we would like the portal to load in under a second. Is there anything we can do to speed up the loading process.

Thank you 
Gilles

**Comment by hannobunjes** [comment]
Hi Gilles,

The delay is mostly due to the way that Angular is loading plugin code, which involves a transpilation step.

With Identity Manager 9,3 we are changing the plugin compilation process to remove that transpilation step. I think the performance improvement will be very noticeable.
