### ISSUE TITLE
EBADENGINE warnings when running npm install

### ISSUE THREAD

**Issue by rogerholtenok** [OneIdentity/IdentityManager.Imx#168]
Hi.

When I run `npm install`, I get a series of EBADENGINE warnings related to the @compodoc/compodoc package. https://github.com/OneIdentity/IdentityManager.Imx/commit/cf9abc607dc8d837c6ff1f76f2961404faac8e88 appears to have updated compodoc to version 1.1.25 which has @angular-devkit/schematics version 18 as a dependency. Angular 18 requires at least Node version 18 while Angular 14, which the portals use, only supports Node up to version 16. We fixed the issue locally by pinning compodoc to version 1.1.23 until the projects are updated to Angular 15 or newer.

Best regards,
Roger

**Comment by Mathnstein** [comment]
Yes Compodoc had given us some trouble on older versions due to security vulnerabilities. With the release of 9.3 we will be supporting Angular 18 and this issue should go away.
