### ISSUE TITLE
Data Source Toolbar - Filter not set initial anymore

### ISSUE THREAD

**Issue by DominicFe** [OneIdentity/IdentityManager.Imx#171]
Hi,

Since the changes which were made on July 3, 2024, I have a problem with the filters. There were changes done at the file "**data-source-toolbar.component.ts**". Since then the filters weren't set initial anymore.

**identities.component.ts**:

this.dataModel = this.isAdmin ? await this.identitiesService.getDataModelAdmin() : await this.identitiesService.getDataModelReport();
      this.filterOptions = this.dataModel.Filters;
      this.groupingOptions = this.getGroupableProperties(this.dataModel.Properties);

      if (!this.isAdmin) {
        const indexActive = this.filterOptions.findIndex((elem) => elem.Name === 'isinactive');
        if (indexActive > -1) {
          this.filterOptions[indexActive].InitialValue = '0';
        }
        const reports = this.filterOptions.findIndex((elem) => elem.Name === 'reports');
        if (reports > -1) {
          this.filterOptions[reports].InitialValue = '0';
        }
      }

In the filterOptions I now always get for "**this.filterOptions[].CurrentValue**" the value "**Undefined**".
![image](https://github.com/user-attachments/assets/01e9215b-7eac-481f-9b75-f9dea7f24223)
 

These filters are not set initial anymore, i always have to select them now manually:

![image](https://github.com/user-attachments/assets/2c7cbeec-fe98-41e0-a60b-b977c965e839)

Regards,
Dominic

**Comment by BertramBo** [comment]
are there any new informations about this issue?

**Comment by Mathnstein** [comment]
Hi @DominicFe - So an easy work around for this would be to just create a view config with the two filters, save it, and mark it as default.

But yes - The more correct solution is that the default for this page have these filters - it appears they were lost in the transition to the view config. I will create an internal ticket.
