### ISSUE TITLE
Infinite request loop when trying to store invalid values

### ISSUE THREAD

**Issue by rogerholtenok** [OneIdentity/IdentityManager.Imx#175]
Hi.

After we updated our portal with the hotfixes dated August 12, we've encountered a bug when trying to modify identities. If we type in an invalid value for a field, like an invalid email address, it's sent with a PUT to the API server as normal. The server responds with an HTTP 500 error and message and the portal then sends an empty PUT to refresh the view. After that, it appears to be stuck in an infinite loop where it keeps sending the same PUT with the invalid value over and over again until we close the identity side sheet.

Best,
Roger

**Comment by hannobunjes** [comment]
Hi @rogerholtenok ,
would you be able to record a HAR file and upload it here?

**Comment by hannobunjes** [comment]
Opened internal bug 465213.
