### ISSUE TITLE
Remove current loggedIn-User as default from "New-Request" by Admin-Portal-Configuration

### ISSUE THREAD

**Issue by gitpm** [OneIdentity/IdentityManager.Imx#177]
In the admin portal I find this option
![image](https://github.com/user-attachments/assets/c3cea348-e0c7-41cb-9536-938a3faef51a)

Selecting / Deslecting this flag does not change the behaviour, that the current loggedIn-User is automatically set in the "New Request" - dialog.
![image](https://github.com/user-attachments/assets/d11c134b-d61f-4096-88cc-09fdb7060eff)

Hence users overread the very tiny hint "(Click to change)" users are overwhelmed to click this button.
So it was to decided to remove the  current loggedIn-User  so users are always fored to select a recipient.

This is my current simple solution -> screenshot
![image](https://github.com/user-attachments/assets/f4ea505d-6ea5-410f-81cc-4d32a5f99754)

This is my current solution -> files
[new-recquest-recipient-solution.zip](https://github.com/user-attachments/files/16793032/new-recquest-recipient-solution.zip)

Maybe you can activate the flag from in a future version for frontend.
Thx
Peter

**Comment by hannobunjes** [comment]
Hi @gitpm ,

This configuration setting is a leftover (indeed its setting has no effect), and it has been removed in more recent versions.

**Comment by hannobunjes** [comment]
For user experience reasons, it was decided against supporting an "empty recipient state" (which forces users to select recipients first).

**Comment by arafatomer66** [comment]
![image](https://github.com/user-attachments/assets/1724b731-1e22-46d5-8d9c-2b03b73bd884)

how to enable this logic where as a session user i can request for other recipients also?

@hannoquest
