### ISSUE TITLE
Error when accessing Filter in Report

### ISSUE THREAD

**Issue by iCC-MK** [OneIdentity/IdentityManager.Imx#178]
Hi,

I encountered a potential bug when trying to access the filter functionality in our reports.

To reproduce this, you need to have a subscribed report and view it via `Profile -> Report Suscriptions -> Actions -> Show report`.
Once I try to click the DataTables Filter-Button in this panel, I get an APIServer error because the portal is trying to access `portal/dynamicgroup/sqlwizard/tables/non_static_table/columns`, because "non_static_table" isn't a valid table.

If you have any questions or problems reproducing it, I'd be glad to help.

Thanks and have a great week.

**Comment by Mathnstein** [comment]
Yes - that endpoint is missing, unsure if we have filters here. Will have someone look into it!

Ticket #472274
