### ISSUE TITLE
Attestation Case Details: Hyperview tab not visible

### ISSUE THREAD

**Issue by iCC-MK** [OneIdentity/IdentityManager.Imx#182]
Hi OneIdentity Angular Team!

At my customer I just got the request to add a hyperview tab to the "View Attestation Case Details" sidesheet(s). After looking at the code, I found that (at least in the `att/src/lib/decision/attestation-case.component.html`) the tab is already there! Unfortunately the condition seems to be wrong:

![image](https://github.com/user-attachments/assets/dc082cd4-3750-4e45-8b56-877a7350b458)

The proper condition seems to be `*ngIf="relatedOptions.length > 0"` because we're already in the "this"-context. I omitted the questionmark, because the property is always declared and an empty array if the data is not loaded yet. After compilation the hyperview tab was visible and fully functional for me.

If you have any questions, feel free to get in touch.

Thanks and have a great day,
Marco

P.S. Since my usecase would also require to have the hyperview tab in the `att/src/lib/attestation-history/attestation-history-details/` component, I'd love to see this as a new feature, since it's already implemented in a pretty similar view. :-)

**Comment by Mathnstein** [comment]
Hi @iCC-MK - Angular is a bit funny on the use of _this_ within templates. It actually could go either way, although for consistency we should not use _this_ within a template.

From a dev environment I see v92 and v93 hyperviews being available on the attestation-case sidesheet. I even see it already on the attestation-history-details component in v93 ;)

If you use the latest code (v92 or v93), do you still see the hyperview not appearing?

**Comment by iCC-MK** [comment]
I just pulled the latest v92 branch and can confirm that it's working now. Really looking forward to the v93 portal. :D

Thanks again!
