### ISSUE TITLE
Attestation Run Details: Attestation cases list unfiltered

### ISSUE THREAD

**Issue by iCC-MK** [OneIdentity/IdentityManager.Imx#184]
Hi again!

I probably found another bug while migrating from the old webportal.

Steps to reproduce:
1. Access "Attestation->Attestation runs"
2. Open the details of one attestation run by clicking on it
3. Open the "Attestation cases" tab

Once there, the list contains **all** entries of the AttestationCase table, even though it should only show the related cases.
The API request looks correct and contains two filters (UID_AttestationRun and UID_AttestationPolicy) and the APIServer's response is empty (which also shouldn't be, because I find some entries using the filters in the ObjectBrowser).

If you need further clarification or some screenshots, please get in touch. Don't want to send them here because of privy data.

Thanks and have a great day,
Marco

**Comment by hannobunjes** [comment]
Hi @iCC-MK ,

This is handled by the internal bug 469379.

Thanks.
