### ISSUE TITLE
Edit Shopping Cart: Assignment of "" to the "" business role

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#185]
9.2.1 (September 9, 2024)
When a user edits his Shopping Cart item (in this example business role)
The "Edit Product" sidesheet shows: Assignment of "" to the "" business role
![image](https://github.com/user-attachments/assets/985ab96a-5dbe-43d8-97d3-c2fdec434e20)

This looks to be an apiserver issue with the QER.CompositionApi.Server.PlugIn given the response:
/apiserverdev/portal/cartitem/interactive/aa55660a-f0bb-4eb7-9326-0028f2a
`"Columns": {
        "Assignment": {
            "Value": "Assignment of \"%ElementAssigned%\" to the \"%ElementAssignedTo%\" business role",
            "IsReadOnly": true
        },`

Regards,
Niels

**Comment by hannobunjes** [comment]
I have not seen this issue reported internally or by anyone else, so I would suspect a data or permissions problem. Please open a support case if you need us to investigate this further.
