### ISSUE TITLE
CDR editor support for Binary columns?

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#186]
It looks like the CDR editor handles all binary columns with the EditImageComponent.

qbm\src\lib\cdr\default-cdr-editor-provider.ts
`if (type === ValType.Binary) {
      return this.createBound(EditImageComponent, parent, cdref);
    }`
    
There is an EditBinaryComponent but it's not used
qbm\src\lib\cdr\edit-binary\edit-binary.component.ts

`export class EditBinaryComponent implements CdrEditor {
  public readonly control = new UntypedFormControl({ value: undefined, disabled: true });
  // TODO: TFS 806165 "imx-web: Editor für Binärdaten verbessern" umsetzen `
  
  Will the CDR EditBinaryComponent be extended/implemented to support up-/download of various filetypes  in the near future?
[This question was also asked on the forum](https://www.oneidentity.com/community/identity-manager/f/forum/37950/field-binary-in-a-new-angular-web-portal-form)

 Regards,
 Niels

**Comment by hannobunjes** [comment]
Hi @NielsDeGroot ,

This is on the internal backlog, but there is no ETA for this feature at this time.
