### ISSUE TITLE
In the new request for multiple recipients, the "Add to Cart" feature is failing for users other than the session user.

### ISSUE THREAD

**Issue by arafatomer66** [OneIdentity/IdentityManager.Imx#189]
![image](https://github.com/user-attachments/assets/0edd92f9-3703-4c00-af23-5110bcba551a)

I requested add to cart for somebody else as recipient along with me. my session user. Mine is added to cart but other recipient's item is not added to cart. It showing 500 error for portal/cartitem api.

**Comment by hannobunjes** [comment]
Hi @arafatomer66 ,

This repository is mainly for discussion and troubleshooting of Angular code in this repository.

If you are getting a HTTP 500 error for an API request, please take a look at the server log which usually contains additional information.

To troubleshoot issues on the server side, please contact support.

**Comment by arafatomer66** [comment]
No i want to know if the angular portal default codebase allow a session user to request item for anybody else! (basically other recipents)

**Comment by hannobunjes** [comment]
Yes, it does. It supports the same functionality as the out-of-the-box Angular applications.

**Comment by arafatomer66** [comment]
Do i have to configure anything from back end side because from angular portal in default codebase it's not working right now!

**Comment by arafatomer66** [comment]
resolved!
