### ISSUE TITLE
Data Source Toolbar - Options

### ISSUE THREAD

**Issue by DominicFe** [OneIdentity/IdentityManager.Imx#190]
I have a question regarding the options in the data source toolbar. For example in Product Bundles. Here it only shows the filter option:

![image](https://github.com/user-attachments/assets/3b224f2f-6a53-459e-acdb-7723c9d219cd)

But in the code is something different implemented. Here is only search and settings defined. So i am asking why does it not show settings and why is the filter shown? Does this come from somewhere else?

**itshop-pattern.component.ts:**

```
<imx-data-source-toolbar
        #dst
        [options]="['search', 'settings']"
        [settings]="dstSettings"
        (search)="getData({ search: $event })"
        (navigationStateChanged)="getData($event)"
        data-imx-identifier="itshop-pattern-dst"
        [itemStatus]="status"
      >
      </imx-data-source-toolbar>
```
      
I have seen this behaviour also in other classes.

**Comment by Mathnstein** [comment]
Hi @DominicFe - while you are correct that the html does show that we want settings here, the data source toolbar has gone through many revisions and its functionality has changed over time.

Where this input used to be the sole determination on if the icon/functionality would be there now there is more logic to check.

In the current state of v92 the settings choice was removed, but here is the rest of the logic that would determine if the icon would show:
`(hasViewSettings || canExport || canSave) && optionset.has('settings') && initalView === 'table'`

So this table likely didn't have the ability to add columns, save configs or export data, and hence the settings isn't there.
