### ISSUE TITLE
In Add to cart section's Edit product, Reason field is not required although showing required (*)

### ISSUE THREAD

**Issue by arafatomer66** [OneIdentity/IdentityManager.Imx#191]
![image](https://github.com/user-attachments/assets/050d7599-d9e5-4ab9-8a7b-ebdb6a1e65e9)

in the "Add to Cart" section, the session user can submit a request without filling out the "Reason" field for the products. The "Reason" field is marked with an asterisk (*), indicating it is required and should be enforced as mandatory while submitting, similar to the behavior in the V8 portal.

Is this the default behavior in V9? If yes, what configurations are needed to make the "Reason" field required?

**Comment by NielsDeGroot** [comment]
In my OOTB setup the Reason field of the ShoppingCartItem is not set to mandatory.
Did you maybe customize the value MinLen (Min. Length) on OrderReason@ShoppingCartItem (default = 0) or something in the angular project?

Try this for a better user experience:
Create a new Request property (new definition)
On the parameters tab click Add
Parameter name = OrderReason
Parametert type = User prompt
Display name = Reason
Mandatory parameter = Yes
Save and set this "Request property" on the service item.
than perform iisreset or reclycle apppool.

**Comment by arafatomer66** [comment]
Thanks for the answer!

**Comment by arafatomer66** [comment]
resolved
