### ISSUE TITLE
"DataTable->Export Data" missing additional columns

### ISSUE THREAD

**Issue by iCC-MK** [OneIdentity/IdentityManager.Imx#193]
**Internal issue created: 472174**

Hi again!

My client stumbled upon an issue regarding the "Export Data" functionality in some tables, that I think is probably not intended.

**Description:** When adding new columns to existing tables via web config param, these columns aren't automatically added to the "Export"-functionality of the respective table.

**Steps to recreate:** Use the "ServerConfig/ITShopConfig/HistoryViewConfiguration/AdditionalTableColumns" web config parameter to add new columns to the request history table. Then try to use the "Export Data" functionality on this table.

**Expected behaviour:** The added columns should also be set in the "Export Data" dialog.

Thanks and have a great day,
Marco

**Comment by Mathnstein** [comment]
Hi @iCC-MK - this is a bug, we have someone on it!
