### ISSUE TITLE
Passcode Generation by a session user for All Identities from Angular Web Portal Feature? 

### ISSUE THREAD

**Issue by omer-arafat** [OneIdentity/IdentityManager.Imx#196]
In the current out-of-the-box feature, a user can only generate passcodes for their subordinates. For example, in the Angular dashboard, under the "My Responsibilities" tile, it lists:

    User 1
    User 2

As a user, I can generate a passcode for these individuals by going to their identity details and selecting "Create Passcode."

<img width="515" alt="Screenshot 2024-10-23 at 10 42 23 PM" src="https://github.com/user-attachments/assets/1bb8e9dc-ff87-4c12-b387-4171d93e91b8">

However, my client wants to enable the ability for a user to generate passcodes for all identities, not just their subordinates. This functionality isn't working out of the box. 

My question is: How can I enable the functionality for a session user to create passcodes for all identities in the Angular web portal?

**Comment by MatthiasBauer** [comment]
1. This place is not any kind of community, support portal replacement or place for enhancement requests
2. for security reasons at this place this feature is only allowed for managers generating a password for the reports
3. a "for all identities" feature is available in the operations support web portal for a dedicated ghroup of pof people only. See https://support.oneidentity.com/technical-documents/identity-manager/9.2/operations-support-web-portal-user-guide/4#TOPIC-2085737
