### ISSUE TITLE
Inactivity timeout in angular portal

### ISSUE THREAD

**Issue by arafatomer66** [OneIdentity/IdentityManager.Imx#197]
is there any feature available in the Angular portal that will terminate a user's session if they are inactive for a certain period of time, requiring them to log in again to access the portal?

- Session timeout 
- inactivity timeout

**Comment by omer-arafat** [comment]
@HerwigAbele @dbarentine @hannoquest @petrsnd

**Comment by hannobunjes** [comment]
Hi @arafatomer66 ,

There is an inactivity timeout, but that is managed by the API server and/or the external IDP.

**Comment by arafatomer66** [comment]
Thank you for the reply!

I have a quick question to clarify a few things.

I found a configuration parameter in QBM/ApiServer/Defaults/SessionLifetime. Is this the configuration you mentioned previously when referring to the API server (which is applied to the Angular portal)?

If I change this to a different value, will it be immediately applied to Angular?

If I'm mistaken, could you please let me know where the inactivity timeout duration can be enabled or modified? example, like if i want to make the inactivity timeout for angular portal duration 20 mints, how to configure it!

Thank you!

@hannoquest

**Comment by arafatomer66** [comment]
@hannoquest

**Comment by hannobunjes** [comment]
Hi @arafatomer66 ,

The server session does apply to Angular, but is not managed by Angular in any way. Please open a support case if you have not already done so, as we cannot provide support for the API here. Thanks.

**Comment by arafatomer66** [comment]
Thanks!
