### ISSUE TITLE
New Request - Request Details: Format Check Fail

### ISSUE THREAD

**Issue by MirkoMiCC** [OneIdentity/IdentityManager.Imx#201]
For example, in a text field input '1'  is not allowed, an error/warning message is shown below the text field, which is correct so far.
But when you remove/replace it by allowed character(s) it still shows the error/warning message.

**Comment by hannobunjes** [comment]
@MirkoMiCC This behavior is fixed in 9.2.1. Please contact support (as I think you have already done) to get a fix.
