### ISSUE TITLE
Condition for request renewal

### ISSUE THREAD

**Issue by SKABechtle** [OneIdentity/IdentityManager.Imx#205]
Hello,
I have the need to have the authorization orders carried out by the service desk for a customer.
In the “old” WebDesigner web portal there was a configuration parameter for this, which I cannot find in Angular Web.
Is it not currently possible to adjust this authorization, or am I just not finding the right point?

Thank you very much!

**Comment by hannobunjes** [comment]
Hello @SKABechtle ,

I am not totally sure but this may be the configuration key you are looking for:

VI_ITShop_Filter_PersonOrderFor
( Specify for which identities requests can be placed. )

Since this question is not really related to Angular because the configuration layer is defined on the server side, the best course of action would be to contact support.

**Comment by SKABechtle** [comment]
Hello Hanno,
that is the configuration parameter from the WebDesigner web portal, so you are correct.
I would now like to know whether there is a configuration parameter in the Angular Web “Administration Portal” to define who can renew an request.

**Comment by hannobunjes** [comment]
Yes, there is. In the Administration Portal, go to *Configuration*, select the *Portal* project and search for `VI_ITShop_Filter_PersonOrderFor`.

**Comment by SKABechtle** [comment]
Hi @hannoquest 
We have already adjusted this configuration parameter.
![image](https://github.com/user-attachments/assets/4ae364b4-aa10-49c5-9cfc-7d6264727546)

The option to renew an active request is still not available (the button is not displayed).
![image](https://github.com/user-attachments/assets/fdbe2806-8e53-4a54-a2b7-a4c7121bfe62)

**Comment by hannobunjes** [comment]
@SKABechtle 
Depending on the version you may need a hotfix for the bug ID 36058. Additionally, the user will also need write permissions on the request object.

**Comment by SKABechtle** [comment]
@hannoquest 
Thank you for the feedback.
I will check the hotfix and contact support if necessary.
