### ISSUE TITLE
CDR imx-edit-fk cannot be changed after wrong input

### ISSUE THREAD

**Issue by BertramBo** [OneIdentity/IdentityManager.Imx#206]
if i typed a wrong search string in a edit-fk CDR with no results like this
![image](https://github.com/user-attachments/assets/1c6122a0-9784-4491-9316-38fbd9c0b36d)

and then typed a new character in the input box i channot change this Field anymore
![image](https://github.com/user-attachments/assets/1a6c4bcb-db17-447b-b2c7-22ea81567a6b)

my workaround at the moment is in the edit-fk.component.ts change the hasCandidatesOrIsLoading() to this 

  _public get hasCandidatesOrIsLoading(): boolean {
    return (
      this.candidatesTotalCount > 0 ||_
      this.columnContainer?.fkRelations?.length >= 1 ||

i have tested this with actual v92 branch.

**Comment by Mathnstein** [comment]
Yes I see this as a bug - will create an internal ticket for this. Strange but good catch!

Ticket #472268
