### ISSUE TITLE
Almost all components that use imx-data-table or imx-data-source-toolbar call their GET endpoint twice

### ISSUE THREAD

**Issue by jd-igf** [OneIdentity/IdentityManager.Imx#214]
Almost all components that use imx-data-table or imx-data-source-toolbar call their GET endpoint twice.

![image](https://github.com/user-attachments/assets/0239f979-5a47-41f9-8e7f-9897a551acc8)

**Cause explained using the example of identities.component:**
In the OnInit of the components, navigate is called. This triggers the GET endpoint. Then, the DataSourceToolbarComponent.updateNavigateStateWithFilters emits navigationStateChanged again, causing navigate to be called once more and thus the GET endpoint is triggered again.

Among other things, the dataSourceHasChanged check in DataSourceToolbarComponent.ngOnChanges doesn’t seem to fit. I suspect it should be something like this:

```typescript
this.dataSourceHasChanged = !(isEqual(changes['settings'].currentValue?.entitySchema
, changes['settings'].previousValue?.entitySchema
));
```

However, that does not seem to be the root cause.

**Comment by rogerholtenok** [comment]
We ended up adding a dirty workaround in navigate where it skips calling getAllPersonAdmin/getReportsOfManager and instead just passes an empty data object to this.dstSettings.dataSource the first time it's called after the component is created.

Having a fix for DataSourceToolbarComponent itself that would fix it for all views would be preferrable.

**Comment by Mathnstein** [comment]
This is a known issue and is being worked on in an internal ticket 469349. Its being tested extensively, but will be fixed soon.
