### ISSUE TITLE
"Valid until"-Date does not show the time

### ISSUE THREAD

**Issue by gitpm** [OneIdentity/IdentityManager.Imx#215]
**Internal Issue created: 473011**

In the standard-ui the user is confused about the timepoint of "**Valid until**"
So user does not know,  if the "Valid until"-Date means till beginn of day or till end of day.
![image](https://github.com/user-attachments/assets/22d559e5-6614-4fd3-affb-2db09e960dec)

A better approach would be,  if the user would be is displayed the concret "time point" of the valid until date.
Hence the date format of "valid until" means always means “end of date”, we decided to display the "end of day"- time to the user.

![image](https://github.com/user-attachments/assets/6985d923-a5f9-45a3-9253-4f1e1790ca59)

I approached this by adding a new flag "withTimeEndOfDay" to date.component.ts
` @Input() public withTimeEndOfDay = false;`

In the ngOnInit - function I configured the DateParser to time parse date string
`  public ngOnInit(): void {
    this.parser = new DateParser(this.logger, this.withTime || this.withTimeEndOfDay);`

With the handleControlChanged() I forced to re-render the ShadowText-FormControl
`    if ( this.withTimeEndOfDay) {
      this.updateShadowText(this.getDateTextFromControl());
    }`

With the getDateTextFromControl()-Function I added the "End-of-Day"-Value to the current value (if exists)
`    let value = this.control?.value as Moment;
    if (value && this.withTimeEndOfDay) {
      value = value.hour(23).minute(59);
    }
    return this.parser.format(value);`
    
   and I guess that's it !!!
   
 The only thing I cannot do, is to set a metadata flag in the in the composition API which flags that the dedicated "Valid Until"-column should be displayed as a "end of day" - imx-date control. 
This  meta data attribute is missing, and I can't customize, because in my opinion metadata customization is not possible at all  in the composition API. Hence this feature is missing in  composition API I decided to display the "Valid Until"-column  as a "end of day" imx-date-control more or less hardcoded in the frontend-ui

**Comment by Mathnstein** [comment]
Hi @gitpm, I like this as well - I would do it perhaps a bit differently knowing there is a [new material component for this](https://material.angular.io/components/timepicker/overview)

But I will mark it as a feature enhancement.
