### ISSUE TITLE
Access to Request history from start page using "my open requests" is not applying filter when user has custom default view

### ISSUE THREAD

**Issue by asattler** [OneIdentity/IdentityManager.Imx#217]
**Internal Issue created: 473012**

Hi guys,

when you have running requests there is a badge on the start screen showing "my open requests", which you can click to access the request history with a filter to be applied on opening the component.
This doesn't work if the user has modified the viewconfiguration and set it to be used as default.
Reason is obvious in request-table.component.ts in function "updateFiltersFromRouteParams".
`if (this.viewConfigService.isDefaultConfigSet()) {
      // If we have a default config, we won't set our filters
      return;
    }`

From my point of view this logic is wrong, as I expect the  filters to be applied when using the link on my start screen...

Can you please check and open an internal ticket for this?

Thanks in advance

**Comment by Mathnstein** [comment]
Hi @asattler 

I would agree that we do need to have a clear priority here - having links refer to pages that set filters steps on the idea of default configs.

I'll open an issue.
