### ISSUE TITLE
Accessibility requires an alt-Tag for an image.

### ISSUE THREAD

**Issue by gitpm** [OneIdentity/IdentityManager.Imx#219]
**Internal Issue created: 473380**

[mast-head.component.html](https://github.com/OneIdentity/IdentityManager.Imx/blob/v92/imxweb/projects/qbm/src/lib/mast-head/mast-head.component.html)

`  <img class="custom-logo" *ngIf="logoUrl" [src]="logoUrl" data-imx-identifier="masthead-custom-logo" 
    tabindex="0" (keydown.enter)="goHome()" (click)="goHome()"  />`

Accessibility requires an alt-Tag for an image.
Better:

` <img class="custom-logo" *ngIf="logoUrl" [src]="logoUrl" data-imx-identifier="masthead-custom-logo" alt="One Identity Logo"
    tabindex="0" (keydown.enter)="goHome()" (click)="goHome()"  />`

**Comment by Mathnstein** [comment]
Hi @gitpm - Yes this is correct, good catch!
