### ISSUE TITLE
Hotfix Request

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#49]
We are based on v8.2.1 and also the Rollup package for 8.2.1 (338550) is installed.
In the meantime we have reported some issues and got fixes from support and have them tested successfully.

If we load the fixes, in one hand the fix the reported problem, but in the other hand, they are overwriting our solution that we have built on this repository.

Question: Can we get the following fixes in this repository v82?

Hotfix 35647 - Password questions are still available under profile in web portal even if the corresponded parameter is set on false.
Hotfix_35658 - Customized Logo is not clickable.
Hotfix_35659 - Tooltip is showing the technical term of the Angular definition
Hotfix_35778 - Delegation: class roles without responsible roles are shown wrong

Thank you

**Comment by zime-rch** [comment]
> Can we get the following fixes in this repository v82?
> 
> Hotfix 35647 - Password questions are still available under profile in web portal even if the corresponded parameter is set on false. Hotfix_35658 - Customized Logo is not clickable. Hotfix_35659 - Tooltip is showing the technical term of the Angular definition Hotfix_35778 - Delegation: class roles without responsible roles are shown wrong

We have verified once again, and I can confirm that the mentioned fixes are already included, so the issue can be closed.

**Comment by hannoquest** [comment]
Thanks for confirming! We will add the list of included fixes soon.
