### ISSUE TITLE
Identity Manager 9.1 - qer-app-portal attestation TypeError

### ISSUE THREAD

**Issue by Alixchau** [OneIdentity/IdentityManager.Imx#68]
Hi Team,
We have a Type Error when implementing app portal in the attestation function. Please find below for more information.

**Versions**
Version: IdentityManager.Imx-91
Application: qer-app-portal
Library and Plugin used: qbm, qer, att

**Describe the Bug:**
From Attestation menu click the pending attestation submenu, and toggle the 'Show attestation cases to be approved by chief approval team', then the TypeError will show up: 'TypeError. Cannot read properties of undefined(reading 'ColumnName')

![Screenshot 2023-03-17 143045](https://user-images.githubusercontent.com/86642948/226033134-07b36c1a-99ec-49c3-b4c7-3c8741b671ad.png)
![Screenshot 2023-03-17 143050](https://user-images.githubusercontent.com/86642948/226033333-9f2e9703-2609-4be4-9afa-80c499e6a898.png)

**Other inforamtion:**
1. There are data comes back from backend, you may see the data object in Preview tab.
2. We tried to locate the root of bug and looks like there's undefined property in getData function in attestation-decision.component.ts (see image below)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/86642948/226034818-1773323a-9b42-4010-91ff-daa9e02ec60b.png)

Thanks for you help!

**Comment by ppslde** [comment]
Hi Alix,

are there any code changes you made? If yes, can you please share them?

Thanks
Regards

**Comment by Alixchau** [comment]
Hi Team,
There were no code changes made. We only compiled the project and deploy it to our server.
Thank you.

**Comment by ppslde** [comment]
Hi Alix,

ok. In which kind of setup are you trying to run your built att module, an IIS hosted api server or a local server via the imxclient tool?
Can you please describe what you have done to create and deploy the built modules/apps to your api server?

Thank you

**Comment by Alixchau** [comment]
HI ppslde,

We ran into this same error both in Development mode and production mode.  

**Versions used**
Version: IdentityManager.Imx-91 (downloaded from git)
Application: qer-app-portal
Library and Plugin used: qbm, qer, att

**Steps for development mode**
We set up a local API Server using imxclient tool. 
Then ran qbm, qer and att using below command from package.json:
npm run build:watch qbm
npm run build:watch qer
npm run build:watch:dynamic att
npm run start qer-app-portal
After logged in, we navigate to the attestation page and toggle the pending attestation button, the TypeError shows up.

**Steps for Prodcution mode**
We generated build file for the libraries, plugins and app-portal by below command from package.json:
npm run build:lib qbm
npm run build:lib qer
npm run build:lib att
npm run build:app qer-app-portal
Then we copy the the build files to IIS API server and rename the files with prefix "Html_"
After logged in, we navigate to the attestation page and toggle the pending attestation button, the TypeError shows up.

Thank you

**Comment by ppslde** [comment]
Hi Alix,

sorry for the delay. 
I tried the steps you provided here on my end and I do not get this issue on the clean repo.

- Can you please provide the response of the request "<serverurl>/portal/usergroups", to check if the user has the needed permissions?
- Can you provide any more detailed browser log?
- Can analyse the api server log for any errors, which are occurring during this step (IIS or imx-client depending on your setup)?

**Comment by ppslde** [comment]
Closing the issue. Behaviour could not be recreated with the information.
