### ISSUE TITLE
V91 - Compliance Rule Details fail - TypeError: Cannot read properties of undefined (reading 'UiOrderState')

### ISSUE THREAD

**Issue by MagnusID** [OneIdentity/IdentityManager.Imx#77]
- Create a Compliance Rule (2 UNSGroupB)
- Activate the Compliance Rule
- Request the two Groups
- Validate the shopping cart
- The validation shows the expected error
- Click on "View Details"
- Error "TypeError: Cannot read properties of undefined (reading 'UiOrderState')"
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/138860573/f3845639-edfd-43c4-a95a-44414455002b)

**Comment by MagnusID** [comment]
It looks like no rules are returned. 
![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/138860573/b9fec867-3580-45c1-a265-a3515a6ef58e)

**Comment by Mathnstein** [comment]
@MagnusID  I wasn't able to reproduce this in the current code. Is this still an issue or shall I close out this issue?
