### ISSUE TITLE
New Portal 9.2 localhost not working 

### ISSUE THREAD

**Issue by Kerelous-Mouris** [OneIdentity/IdentityManager.Imx#84]
I am facing an issue with the simulation on the localhost, I have followed the steps to download the repo and link it to the APIServer. However, after I compile qbm, qer, and run the qer-app-portal on the localhost, I am not able to login through it. 

It is working properly on the APIServer installed using IDM autorun but the repo is not working. I face the issue while logging in using the same account I use on the direct APIServer. 

Please let me know if I am missing anything related to the prerequisites or how I can solve this issue. 

Here is a screenshot of the error"
![Screenshot (80)](https://github.com/OneIdentity/IdentityManager.Imx/assets/77944444/d35d9402-0073-47a3-9f6a-2cd4e2922a19)

**Comment by gitpm** [comment]
Hi Kerelous, are using a v92 backend? 
I got the same issue when I started with v92 - IdententyManager. Then I realized that I was connected to my v91 - backend instance and fixed it

**Comment by Kerelous-Mouris** [comment]
Actually it is connected to 9.2 backend, and still not working.

**Comment by juancarloscamargo** [comment]
Please, check my post to your question on forum, see if that helps

T*fn:9**57211157 - 650932877*
Información Legal: https://www.eprinsa.es/informacion-legal

**Comment by gitpm** [comment]
... and for the localhost - development you are using the v92 - imxClient?
The thing is: You have to change all your references in the VS project to v92. After I did this the project worked

**Comment by Mathnstein** [comment]
@Kerelous-Mouris has this issue been resolved? I will mark this as stale otherwise.
