### ISSUE TITLE
Attestation menu removed when deploying from repo to APIServer

### ISSUE THREAD

**Issue by Kerelous-Mouris** [OneIdentity/IdentityManager.Imx#85]
I am facing an issue that the attestation menu is removed once I deploy any customization from repos. I have tried v90, v91, v92 and all have the same issue.

I have tried to deploy the default qbm, qer, qer-app-portal without any customizations. Still the same issue.

Did anyone faced the same issue ?  

Before: 
![before](https://github.com/OneIdentity/IdentityManager.Imx/assets/77944444/619f2242-4939-416e-82a7-97bfe07293ef)

After: 
![after](https://github.com/OneIdentity/IdentityManager.Imx/assets/77944444/e5fe4f10-4e02-4529-bc3b-72c53c4ebf4e)

**Comment by mru-ipg** [comment]
Yes, you have to run and build also the att project, but if you want to see the Attestation Menuitem on the Dev-Mode you should just run: `npm run build:watch:dynamic att`

**Comment by Mathnstein** [comment]
@Kerelous-Mouris the solution to run the dynamic build script for dynamic libs in development is correct. `npm run build:watch:dynamic lib` will watch any changes to a dynamic lib and recompile them for the localhost to pick them up, i.e att or cpl.

the `build:watch` script is intended for the static libs like qer or qbm.
