### ISSUE TITLE
Angular One Identity Theming

### ISSUE THREAD

**Issue by mru-ipg** [OneIdentity/IdentityManager.Imx#87]
There is a issue with theming the Portal:

In the console showing an error of refused to apply style from the create theme link.
If you click also on the generated link, there is nothing.

![angular-theming](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/8f933c3b-65b5-4047-a4f4-9dfa9888d98d)

**Comment by Mathnstein** [comment]
Posting images from #90 
![288754995-2025b734-1c54-436f-b56e-27d412182bbe](https://github.com/OneIdentity/IdentityManager.Imx/assets/25921691/0fb6da97-ac8f-4fce-9c7d-d22dcb1db650)
![288756590-c77e623f-6171-4dcb-8227-77fd58bf6393](https://github.com/OneIdentity/IdentityManager.Imx/assets/25921691/481c91ae-f0b5-4056-a89c-d1e0f9b86ff5)
![288756877-7461707c-2909-48b7-a318-d4d668d4247c](https://github.com/OneIdentity/IdentityManager.Imx/assets/25921691/70c8c123-47cd-4770-a6ce-8e1f4d0a2cf4)

**Comment by Mathnstein** [comment]
@mru-ipg could you also provide me your .scss source file? I suspect something went wrong in the setup for the server to be acting like this.

**Comment by mru-ipg** [comment]
@Mathnstein which file from the root Angular project or this which are responsible to create the theme. from the /custom-theme directory?

**Comment by mru-ipg** [comment]
`$theme_font_family: 'Source Sans Pro, "Helvetica Neue", sans-serif' !default;

@use 'sass:math';
@use '@angular/material' as mat;

@import '@elemental-ui/core/src/styles/functions/to_number';

@import '@elemental-ui/core/src/styles/reset';
@import '@elemental-ui/core/src/styles/billboard';
@import '@elemental-ui/core/src/styles/cadence';
@import '@elemental-ui/core/src/styles/material_icons';
@import '@elemental-ui/core/src/styles/source_sans_pro';
@import '@elemental-ui/core/src/styles/palette';
@import '@elemental-ui/core/src/styles/typography';
@import '@elemental-ui/core/src/styles/material_fixes';
@import '@elemental-ui/core/src/styles/inputs';
@import '@elemental-ui/core/src/styles/clickables';
@import '@elemental-ui/core/src/styles/common';

$custom-typography: mat.define-typography-config(
  $font-family: $theme_font_family,
  $button: mat.define-typography-level(14px, 14px, 400),
);
@include mat.core($custom-typography);

// Define the custom theme.
$primary: mat.define-palette($gunmetal-palette);
$accent: mat.define-palette($corbin-orange-palette);
$warn: mat.define-palette($phoenix-red-palette);

$theme: mat.define-light-theme(
  (
    color: (
      primary: $primary,
      accent: $accent,
      warn: $warn,
    ),
  )
);

.space-theme {
  @include mat.all-component-themes($theme);
}`

**Comment by mru-ipg** [comment]
@Mathnstein i did all like you have mention on the README file

**Comment by Mathnstein** [comment]
@mru-ipg That .scss file is defining a "space-theme" which is what the readme says to do - but it is important the configuration matches as you have defined something as "my-theme" from your pictures.

I suspect the url isn't being found and thats resulting in your error.

`{
    "Themes": [
        {
            "Name": "space-theme",
            "Display Name": "Space Theme",
            "Class": "space-theme",
            "Urls": [
                "../space-theme/custom-theme.css"
            ]
        }
    ]
}`

@hannoquest would you agree?

**Comment by mru-ipg** [comment]
And where should it be in the root of the angular Project?
I did it several times, every time shows me up this error.

Kind Regards
@Mathnstein @hannoquest

**Comment by Mathnstein** [comment]
@mru-ipg once you have built the custom theme via the npm build script as specified in the readme, zipped and created the corresponding configuration .json

Then within your assemblies distribution:
`assemblies`
-- `imxweb`
---- `Html_<name of theme>.zip` <-- contains the .css code
---- `Html_<name of theme>`
------ `imx-theme-config.json` <-- Tells the API server how to load this theme and apply it's contents

So the content of this **does not** live within the angular project itself, but within the API server

**Comment by mru-ipg** [comment]
@Mathnstein 

I have still the issues with the custom theme.

![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/bcf12a02-e734-4349-89a1-9974a5698cf1)

**Comment by Mathnstein** [comment]
@mru-ipg I'm seeing the api call refer to 4200 -> the file look up should be on 8182 within the api server.

These files don't live within imxweb but within the imxclient/api server.
