### ISSUE TITLE
Changes in billboard.js break the project

### ISSUE THREAD

**Issue by SlamWeasel** [OneIdentity/IdentityManager.Imx#88]
(v91)
Due to billboard.js removing LineOptions, the project cant compile anymore.

To fix the issue, the package.json can just say "3.1.3", instead of "^3.1.3"

Credit to Juancarlos Camargo for finding this fix: https://www.oneidentity.com/community/identity-manager/f/forum/35751/html5-development-in-9-1-adding-custom-imx-api-ccc-tgz-breaks-compilation

**Comment by Mathnstein** [comment]
Good catch. Internal ticket 441048
