### ISSUE TITLE
Changing of Password Questions not possible in Password Reset Portal (Version 9.2)

### ISSUE THREAD

**Issue by nicolasbreuni** [OneIdentity/IdentityManager.Imx#89]
![2023-11-22 18_24_35-One Identity Manager Kennwortrücksetzungsportal - Brave](https://github.com/OneIdentity/IdentityManager.Imx/assets/42643976/959777ef-b047-4656-bea0-4ff695c2ea90)

When opening this page I get the following errors:
![2023-11-22 18_28_52-One Identity Manager Kennwortrücksetzungsportal - Brave](https://github.com/OneIdentity/IdentityManager.Imx/assets/42643976/eb6c4c98-66d8-49b1-b2d4-580b434c783e)

**Comment by Mathnstein** [comment]
@nicolasbreuni it looks like this bug was reported and fixed already, the next code sync on github should contain this fix.

Work item 434134.
