### ISSUE TITLE
Default theme not being applied (9.2)

### ISSUE THREAD

**Issue by Fu7ure** [OneIdentity/IdentityManager.Imx#90]
Hey, thanks for the new support for custom themes in 9.2!

The implementation worked exactly as intended up until the point where we tried to set our new custom theme as the default theme. 

Even though our custom theme is listed and selected as the value of the new config param "ServerLevelConfig/DefaultHtmlTheme", it seems to be completely ignored by the angular portal. The default theme is still the standard light blue one.

![image](https://github.com/OneIdentity/IdentityManager.Imx/assets/57093836/0f7d9712-5aef-4b69-9139-f226f383b243)

**Comment by mru-ipg** [comment]
I had this problem while im trying to set cusotm theme.

![281011751-8f933c3b-65b5-4047-a4f4-9dfa9888d98d](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/ed372c07-488f-4f7c-8a01-c052e8556e6a)

**Comment by Mathnstein** [comment]
@Fu7ure  I was able to reproduce this issue in v92 - internal ticket is 441217.

@mru-ipg I haven't been able to see any MIME typing issues, do you have a repro or was this a one-off error?

**Comment by mru-ipg** [comment]
@Mathnstein i checkeck it again and i have still the same issue with theme, i don`t know why?

![mimetype-bug](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/2025b734-1c54-436f-b56e-27d412182bbe)

![css-bug](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/c77e623f-6171-4dcb-8227-77fd58bf6393)

![bug-prblem](https://github.com/OneIdentity/IdentityManager.Imx/assets/148050877/7461707c-2909-48b7-a318-d4d668d4247c)

**Comment by Mathnstein** [comment]
@mru-ipg  I see you had another issue on this topic open. I will close out this issue with the creation of the internal ticket for @Fu7ure .

We will continue the discussion on this on ticket #87

**Comment by iCC-MK** [comment]
Is there a rough timeframe on when a fix for this issue will become available, or is there some kind of workaround in the meantime? It's quite the obstacle for our go-live.

If there's no timeframe, is it possible to track the internal ticket in the support portal maybe?

Thanks for the support!

**Comment by Mathnstein** [comment]
@hannoquest could you provide more detail here?

@iCC-MK as for the internal work I can see a fix has been made and it is now in testing with QA.

**Comment by hannobunjes** [comment]
We will update the source code here are soon as the fix has been tested internally. Hopefully that will happen early next week.
