### ISSUE TITLE
Missing metadata in IEntityColumn

### ISSUE THREAD

**Issue by MatthiasiCConsult** [OneIdentity/IdentityManager.Imx#93]
Hey there,
since the update 9.2 some of the previously available metadata is not there anymore. We created a customization for the cdr-editor component. We display a tooltip which is the description of the column. Unfortunately since the update we cannot access the description of the column, it returns `undefined`.

```js
this.cdr?.column?.GetMetadata().GetDescription();
```
column is `IEntityColumn`
GetMetadata() is `IValueMetadata`

We tracked the traffic and the description is in the data send to the frontend. Even though it is there it is somehow ignored and not available via the given way (which used to work). Is that intentional or a bug? If it is intentional, is there a different way to get the description?

In Regards
Matthias Hauer (ic Consult)

**Comment by Mathnstein** [comment]
Hi Matthias,

I dug into this a big and you are correct - some of this behavior did change on the server side from 91 to 92. I suggest filing a server bug with support here: https://support.oneidentity.com/
