### ISSUE TITLE
An error occurred while processing your request: OnlyDirect=true&PageSize=10000&isinactive=0

### ISSUE THREAD

**Issue by NielsDeGroot** [OneIdentity/IdentityManager.Imx#98]
9.2 Release update: January 16, 2024
Related to: Bug 441320: Inactive identities listed in "My Direct Reports" start page tile but not if you follow the "VIEW" link of that tile?

When logged in as a manager (uid_personhead) of person:
TypeError: Cannot read properties of undefined (reading 'length')
'My Direct Reports' is empty

Message in server log:
https://itshop.groot.net/apiserverdev/portal/person/reports?OnlyDirect=true&PageSize=10000&isinactive=0
403 forbidden [{"Message":"An error occurred while processing your request.","Number":0}]

If you remove the 'isinactive=0' part
https://itshop.groot.net/apiserverdev/portal/person/reports?OnlyDirect=true&PageSize=10000
{"TotalCount":1,"TableName":"Person","Entities":[]}

projects\qer\src\lib\wport\businessowner-chartsummary\businessowner-chartsummary.component.ts
Line 170: isinactive: '0'

Regards,
Niels

**Comment by Mathnstein** [comment]
An internal ticket has been created for this - 443940

**Comment by hannobunjes** [comment]
Hi @NielsDeGroot 
Please contact support to get a hotfix for the bug 441320.
Thanks!
